import type { Metadata } from "next";
import "../css/globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import LayoutClient from "./layout2";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Quang",
  },
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutClient>
      {children}
      <Toaster position="top-right"  />
      </LayoutClient>
  );
}
